export const responses = [
  `You weren't supposed to do that.`,
  `Please do not click the button again.`,
  `You clicked the button. You rebel.`,
  `You weren't supposed to click the button.`,
  `STAHHHHP!`,
  `The button hasn't been clicked since the last time.`,
  `Every time I hear that button, it's been clicked.`,
  `You clicked the button. Daring.`,
  `Your lack of discression is disappointing.`,
  `You do not want to know what just happened.`,
  `That was a bad idea.`,
  `Did you want to click the button?`,
  `Oh no.`,
  `Please, no.`,
  `😱`,
  `💩`,
  `Really?`,
  `Why?`,
  `Enough already.`,
  `Whyyyyy???!!!!1!!!`,
  `Oh geez.`,
  `Holy buckets.`,
  `Just, stop.`,
  `No more, please.`,
  `What just happened?`
];